Use AndroidX version of JUnit in order to run tests again.
As far as I could understand, back in a95c5522 we switched to AndroidX,
but the statement defining the instrumentation test runner hadn't been
updated. This resulted in the tests failing to run with this error

```
java.lang.RuntimeException: Unable to instantiate instrumentation
ComponentInfo{com.automattic.simplenote.debug.test/android.support.test.runner.AndroidJUnitRunner}:
java.lang.ClassNotFoundException: Didn't find class "android.support.test.runner.AndroidJUnitRunner"
on path: DexPathList[
  [
    zip file "/system/framework/android.test.runner.jar",
    zip file "/system/framework/android.test.mock.jar",
    zip file "/data/app/com.automattic.simplenote.debug.test-NQM1UL3EJ7PNW0zh1s-oFQ==/base.apk",
    zip file "/data/app/com.automattic.simplenote.debug-82lTbOU8tKb6j931lp9neA==/base.apk"
  ],
  nativeLibraryDirectories=[/system/lib]
]
```

Switching to the androidx version fixed the issue.